// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CurrentRuntimeStatus() {
  return window['go']['main']['App']['CurrentRuntimeStatus']();
}

export function GetBasicProxySettings() {
  return window['go']['main']['App']['GetBasicProxySettings']();
}

export function GetOnboardingState() {
  return window['go']['main']['App']['GetOnboardingState']();
}

export function GetRecentLogs(arg1) {
  return window['go']['main']['App']['GetRecentLogs'](arg1);
}

export function GetStatus() {
  return window['go']['main']['App']['GetStatus']();
}

export function OpenConfigFile() {
  return window['go']['main']['App']['OpenConfigFile']();
}

export function OpenLogDirectory() {
  return window['go']['main']['App']['OpenLogDirectory']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function SaveBasicProxySettings(arg1) {
  return window['go']['main']['App']['SaveBasicProxySettings'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function StartCore() {
  return window['go']['main']['App']['StartCore']();
}

export function StopCore() {
  return window['go']['main']['App']['StopCore']();
}

export function ToggleAutoStart() {
  return window['go']['main']['App']['ToggleAutoStart']();
}
