// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {runtime} from '../models';
import {config} from '../models';
import {logs} from '../models';
import {main} from '../models';

export function CurrentRuntimeStatus():Promise<runtime.RuntimeStatus>;

export function GetBasicProxySettings():Promise<config.BasicProxySettings>;

export function GetOnboardingState():Promise<config.OnboardingState>;

export function GetRecentLogs(arg1:number):Promise<Array<logs.Entry>>;

export function GetStatus():Promise<main.AppStatus>;

export function OpenConfigFile():Promise<void>;

export function OpenLogDirectory():Promise<void>;

export function Quit():Promise<void>;

export function SaveBasicProxySettings(arg1:config.BasicProxySettings):Promise<main.SaveBasicProxySettingsResult>;

export function ShowWindow():Promise<void>;

export function StartCore():Promise<void>;

export function StopCore():Promise<void>;

export function ToggleAutoStart():Promise<void>;
